[book]
authors = ["Seasawher"]
language = "ja"
src = "booksrc" # 単に src とすると検索ノイズが多くなることを考慮
title = "Lean by Example"
description = "プログラミング言語であるとともに定理証明支援系でもある Lean 言語と、その主要なライブラリの使い方を豊富なコード例とともに解説した資料です。"

[build]
# ビルドしたファイルを保存するディレクトリ
build-dir = "book"
# ビルド実行時に勝手にファイルを作らない
create-missing = false

[output.html]
additional-js = [
  # コードブロックごとに実行ボタンを表示する
  "assets/blockPlay.js",
  # ページごとに実行ボタンを表示する
  "assets/filePlay.js",
  # 検索機能を改善し、日本語で検索できるようにする
  "assets/fzf.umd.js", "assets/elasticlunr.js",
  # 見出しをMathlhib4Helpへの外部リンクに変換する
  "assets/replaceToLink.js",
  # ランダムページボタンを表示する
  "assets/randomPage.js",
]
additional-css = [
  # フォントと画像の表示を調整する
  "./assets/custom.css",
  # コードブロックのコピーボタンと実行ボタンのサイズをそろえる
  "./assets/codeBlockButtons.css",
]

# セクション番号を振らない
no-section-label = true

# 現在のページの見出しをサイドバーに表示する
sidebar-header-nav = true

# git リポジトリへのリンクを表示する
git-repository-url = "https://github.com/lean-ja/lean-by-example"

# 編集ボタンを上書きして、コード実行ボタンにするための設定
edit-url-template = "https://raw.githubusercontent.com/lean-ja/lean-by-example/main/{path}"

# 404 ページが正常にはたらくようにするために必要
site-url = "https://lean-ja.github.io/lean-by-example/"

[output.html.search]
# 検索したときに、クエリと見出し語が一致していれば見出し語のページがトップに出てくるようにする
boost-title = 25

[output.html.fold]
# 目次の折りたたみの設定
enable = true
level = 0
