import Examples.Aesop
import Examples.Apply
import Examples.ApplyQuestion
import Examples.Assumption
import Examples.By
import Examples.ByCases
import Examples.ByContra
import Examples.Cases
import Examples.Choose
import Examples.Constructor
import Examples.Contradiction
import Examples.Convert
import Examples.Exact
import Examples.Exists
import Examples.Ext
import Examples.Funext
import Examples.Have
import Examples.Induction
import Examples.Intro
import Examples.LeftRight
import Examples.Linarith
import Examples.Rel
import Examples.Rfl
import Examples.Ring
import Examples.Rw
import Examples.Show
import Examples.Simp
import Examples.Sorry
import Examples.Suffices
import Examples.Trivial