import Examples.ApplyQuestion
import Examples.Assumption
import Examples.By
import Examples.ByCases
import Examples.ByContra
import Examples.Cases
import Examples.Choose
import Examples.Clear
import Examples.Command.Check
import Examples.Command.Eval
import Examples.Command.Find
import Examples.Command.Guard
import Examples.Command.Help
import Examples.Command.Instances
import Examples.Command.Print
import Examples.Command.Synth
import Examples.Command.Time
import Examples.Congr
import Examples.Constructor
import Examples.Contradiction
import Examples.Convert
import Examples.Exact
import Examples.ExactQuestion
import Examples.Exists
import Examples.Ext
import Examples.Funext
import Examples.GuardHyp
import Examples.Have
import Examples.Hint
import Examples.Induction
import Examples.Intro
import Examples.LeftRight
import Examples.Linarith
import Examples.Nlinarith
import Examples.Omega
import Examples.PushNeg
import Examples.Refine
import Examples.Rel
import Examples.Repeat
import Examples.Replace
import Examples.Rfl.Refl
import Examples.Rfl.Rfl
import Examples.Ring
import Examples.Rw
import Examples.RwSearch
import Examples.Says
import Examples.Set
import Examples.Show
import Examples.Simp
import Examples.SlimCheck
import Examples.Sorry
import Examples.Split
import Examples.Suffices
import Examples.Tactic.Aesop
import Examples.Tactic.AllGoals
import Examples.Tactic.Apply
import Examples.Tactic.ApplyAssumption
import Examples.Tauto
import Examples.Trivial
import Examples.Try
import Examples.Unfold
import Examples.Wlog
