name: validate installation procedure

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/install.yml'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/install.yml'
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  install_lean_for_windows:
    runs-on: windows-latest
    steps:
      - name: check dependencies
        shell: pwsh
        run: |
          git --version
          curl --version

      - name: install elan
        shell: pwsh
        run: |
          curl -O --location https://elan.lean-lang.org/elan-init.ps1
          pwsh `
            -ExecutionPolicy Bypass `
            -f elan-init.ps1 `
            -NoPrompt:$True `
            -DefaultToolchain:stable
          Remove-Item elan-init.ps1

      - name: modify PATH
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.elan\bin"

      - name: check installation of elan
        shell: pwsh
        run: elan --version

      - name: install latest stable version of Lean
        shell: pwsh
        run: |
          elan default stable
          elan toolchain install stable

      - name: check installation of Lean and lake
        shell: pwsh
        run: |
          lean --version
          lake --version

  install_lean_for_linux:
    runs-on: ubuntu-latest
    steps:
      - name: check dependencies
        shell: bash
        run: |
          git --version
          curl --version

      - name: install elan
        shell: bash
        run: |
          curl -O --location https://elan.lean-lang.org/elan-init.sh
          sh elan-init.sh -y --default-toolchain stable
          rm elan-init.sh

      - name: modify PATH
        shell: bash
        run: echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: check installation of elan
        shell: bash
        run: elan --version

      - name: install latest stable version of Lean
        shell: bash
        run: |
          elan toolchain install stable

      - name: check installation of Lean and lake
        shell: bash
        run: |
          lean --version
          lake --version
