name: Link Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "link-check"
  cancel-in-progress: false

jobs:
  link_check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install elan
        run: |
          curl -O --location https://elan.lean-lang.org/elan-init.sh
          sh elan-init.sh -y --default-toolchain stable
          rm elan-init.sh
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: build markdown files
        run: lake run build_md

      - name: Run Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: "./booksrc/**/*.md"
