name: Generate PDF

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.vscode/**'
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.vscode/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install elan
        run: |
          curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.32'

      - name: build markdown
        run: lake run build

      - name: install fonts and pandoc
        run: |
          sudo apt update
          sudo apt install -y fonts-noto-cjk fonts-ipafont pandoc
          sudo apt install -y --only-upgrade pandoc

      - name: install typst
        run: cargo install typst-cli

      - name: Generate PDF
        run: ./pdf/pandoc.ps1
        shell: pwsh

      - name: Upload PDF to artifact storage
        uses: actions/upload-artifact@v4
        with:
          name: "Lean by Example"
          path: "/pdf/out.pdf"
